-- =============================================================================
-- MIGRAÇÃO: Criar tabelas para extração de lotes de leilão
-- Versão: 1.0
-- Data: 2026-01-25
-- Autor: Tech Lead (Claude Code)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- TABELA: lotes_leilao
-- Propósito: Armazenar lotes individuais extraídos dos editais (relação 1:N)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.lotes_leilao (
    -- Identificadores
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_interno TEXT NOT NULL UNIQUE,  -- SHA256 hash para idempotência
    edital_id BIGINT REFERENCES public.editais_leilao(id) ON DELETE CASCADE,

    -- Dados Brutos (IMUTÁVEIS após inserção)
    numero_lote_raw TEXT NOT NULL,
    descricao_raw TEXT NOT NULL,
    valor_raw TEXT,
    texto_fonte_completo TEXT,  -- Bloco original da extração

    -- Dados Processados (determinísticos)
    numero_lote TEXT NOT NULL,
    descricao_completa TEXT NOT NULL,
    avaliacao_valor NUMERIC,

    -- Dados Enriquecidos (via LLM ou taxonomia)
    categoria_id TEXT,  -- VEICULO, SUCATA, MOTO, CAMINHAO, etc.
    marca TEXT,
    modelo TEXT,
    ano_fabricacao INTEGER,
    placa TEXT,
    chassi TEXT,
    renavam TEXT,
    tipo_venda TEXT,  -- ARREMATE, LANCE MINIMO, etc.
    confidence_score NUMERIC(3,2),

    -- Metadados de Rastreabilidade
    fonte_tipo TEXT NOT NULL,  -- 'pdf_tabela', 'excel', 'csv'
    fonte_arquivo TEXT NOT NULL,
    fonte_pagina INTEGER,
    hash_conteudo_fonte TEXT NOT NULL,  -- SHA256 do texto fonte
    versao_extrator TEXT NOT NULL,  -- 'lotes_extractor_v1'
    familia_pdf TEXT,  -- 'PDF_TABELA_INICIO', 'PDF_TABELA_MEIO_FIM', etc.

    -- Timestamps
    data_extracao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_lotes_edital_id ON public.lotes_leilao(edital_id);
CREATE INDEX IF NOT EXISTS idx_lotes_categoria ON public.lotes_leilao(categoria_id);
CREATE INDEX IF NOT EXISTS idx_lotes_created_at ON public.lotes_leilao(created_at);
CREATE INDEX IF NOT EXISTS idx_lotes_placa ON public.lotes_leilao(placa);
CREATE INDEX IF NOT EXISTS idx_lotes_marca ON public.lotes_leilao(marca);

-- Comentários
COMMENT ON TABLE public.lotes_leilao IS 'Lotes individuais extraídos dos editais de leilão (relação 1:N com editais_leilao)';
COMMENT ON COLUMN public.lotes_leilao.id_interno IS 'Hash SHA256 único para idempotência (edital_id + numero_lote + hash_descricao)';
COMMENT ON COLUMN public.lotes_leilao.numero_lote_raw IS 'Número do lote exatamente como extraído, sem limpeza';
COMMENT ON COLUMN public.lotes_leilao.texto_fonte_completo IS 'Texto original da linha/célula antes de qualquer processamento';

-- -----------------------------------------------------------------------------
-- TABELA: lotes_quarentena
-- Propósito: Dead Letter Queue para lotes que falharam no processamento
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.lotes_quarentena (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edital_id BIGINT REFERENCES public.editais_leilao(id) ON DELETE CASCADE,

    -- Payload Original (para reprocessamento)
    payload_original JSONB NOT NULL,
    texto_fonte_completo TEXT,

    -- Contexto do Erro
    estagio_falha TEXT NOT NULL,  -- 'classificacao', 'extracao', 'validacao', 'enriquecimento'
    codigo_erro TEXT NOT NULL,
    mensagem_erro TEXT NOT NULL,
    stack_trace TEXT,

    -- Metadados
    fonte_tipo TEXT NOT NULL,
    fonte_arquivo TEXT NOT NULL,
    fonte_pagina INTEGER,
    familia_pdf TEXT,
    versao_extrator TEXT NOT NULL,
    tentativas INTEGER DEFAULT 1,

    -- Resolução
    status TEXT DEFAULT 'pendente',  -- 'pendente', 'resolvido', 'descartado'
    resolvido_em TIMESTAMP WITH TIME ZONE,
    resolvido_por TEXT,
    notas_resolucao TEXT,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_quarentena_edital_id ON public.lotes_quarentena(edital_id);
CREATE INDEX IF NOT EXISTS idx_quarentena_status ON public.lotes_quarentena(status);
CREATE INDEX IF NOT EXISTS idx_quarentena_codigo_erro ON public.lotes_quarentena(codigo_erro);

-- Comentários
COMMENT ON TABLE public.lotes_quarentena IS 'Dead Letter Queue para lotes que falharam em qualquer estágio do processamento';
COMMENT ON COLUMN public.lotes_quarentena.estagio_falha IS 'Estágio onde ocorreu a falha: classificacao, extracao, validacao, enriquecimento';

-- -----------------------------------------------------------------------------
-- TABELA: arquivos_processados_lotes
-- Propósito: Rastrear arquivos processados para idempotência
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.arquivos_processados_lotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edital_id BIGINT REFERENCES public.editais_leilao(id) ON DELETE CASCADE,

    -- Identificação do Arquivo
    nome_arquivo TEXT NOT NULL,
    hash_arquivo TEXT NOT NULL,  -- SHA256 do conteúdo binário
    tipo_detectado TEXT NOT NULL,  -- 'pdf_nativo', 'pdf_escaneado', 'excel', 'csv'
    familia_pdf TEXT,  -- Para PDFs: qual família estrutural

    -- Resultados
    total_lotes_extraidos INTEGER DEFAULT 0,
    total_lotes_quarentena INTEGER DEFAULT 0,

    -- Status
    status TEXT DEFAULT 'pendente',  -- 'pendente', 'processado', 'erro', 'escaneado'
    mensagem_status TEXT,

    -- Metadados
    versao_extrator TEXT NOT NULL,
    processado_em TIMESTAMP WITH TIME ZONE,
    tempo_processamento_ms INTEGER,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraint de unicidade
    CONSTRAINT unique_arquivo_hash UNIQUE (hash_arquivo)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_arquivos_edital_id ON public.arquivos_processados_lotes(edital_id);
CREATE INDEX IF NOT EXISTS idx_arquivos_status ON public.arquivos_processados_lotes(status);

-- Comentários
COMMENT ON TABLE public.arquivos_processados_lotes IS 'Rastreamento de arquivos processados para garantir idempotência';
COMMENT ON COLUMN public.arquivos_processados_lotes.hash_arquivo IS 'SHA256 do conteúdo binário - garante que mesmo arquivo não seja processado duas vezes';

-- -----------------------------------------------------------------------------
-- TRIGGERS para updated_at automático
-- -----------------------------------------------------------------------------

-- Função já existe no schema principal, mas garantindo idempotência
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_lotes_leilao_updated_at ON public.lotes_leilao;
CREATE TRIGGER update_lotes_leilao_updated_at
    BEFORE UPDATE ON public.lotes_leilao
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_lotes_quarentena_updated_at ON public.lotes_quarentena;
CREATE TRIGGER update_lotes_quarentena_updated_at
    BEFORE UPDATE ON public.lotes_quarentena
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- VIEWS ÚTEIS
-- -----------------------------------------------------------------------------

-- View: Resumo de lotes por edital
CREATE OR REPLACE VIEW vw_lotes_por_edital AS
SELECT
    e.id AS edital_id,
    e.id_interno AS edital_id_interno,
    e.titulo AS edital_titulo,
    e.cidade,
    e.uf,
    e.data_leilao,
    COUNT(l.id) AS total_lotes,
    COUNT(l.id) FILTER (WHERE l.avaliacao_valor IS NOT NULL) AS lotes_com_valor,
    SUM(l.avaliacao_valor) AS valor_total_lotes,
    COUNT(DISTINCT l.marca) AS marcas_distintas,
    array_agg(DISTINCT l.marca) FILTER (WHERE l.marca IS NOT NULL) AS marcas
FROM public.editais_leilao e
LEFT JOIN public.lotes_leilao l ON e.id = l.edital_id
GROUP BY e.id, e.id_interno, e.titulo, e.cidade, e.uf, e.data_leilao;

-- View: Estatísticas de extração
CREATE OR REPLACE VIEW vw_estatisticas_extracao AS
SELECT
    familia_pdf,
    COUNT(*) AS total_arquivos,
    SUM(total_lotes_extraidos) AS total_lotes,
    SUM(total_lotes_quarentena) AS total_quarentena,
    ROUND(AVG(tempo_processamento_ms)::numeric, 2) AS tempo_medio_ms,
    COUNT(*) FILTER (WHERE status = 'processado') AS processados,
    COUNT(*) FILTER (WHERE status = 'erro') AS com_erro
FROM public.arquivos_processados_lotes
GROUP BY familia_pdf;

-- =============================================================================
-- RLS (Row Level Security) - Segurança
-- =============================================================================

ALTER TABLE public.lotes_leilao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lotes_quarentena ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arquivos_processados_lotes ENABLE ROW LEVEL SECURITY;

-- Service role tem acesso total
CREATE POLICY "Service role acesso total lotes_leilao"
ON public.lotes_leilao FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE POLICY "Service role acesso total lotes_quarentena"
ON public.lotes_quarentena FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE POLICY "Service role acesso total arquivos_processados"
ON public.arquivos_processados_lotes FOR ALL TO service_role
USING (true) WITH CHECK (true);

-- =============================================================================
-- FIM DA MIGRAÇÃO
-- =============================================================================
