-- ============================================================================
-- MIGRACAO 010: Criar tabela staging para dados brutos da API leiloesjudiciais
-- Data: 2026-01-30
-- Autor: Claude Code
-- Descricao: Tabela para armazenar payloads brutos da API antes de normalizar.
--            Usa content_hash para garantir idempotencia.
-- ============================================================================

-- ============================================================================
-- FASE 1: CRIAR TABELA leiloeiro_lotes_raw
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.leiloeiro_lotes_raw (
    -- Identificador primario
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- === IDENTIFICACAO E IDEMPOTENCIA ===
    -- Hash unico do conteudo para evitar duplicatas
    content_hash TEXT NOT NULL,

    -- Identificador do lote na API origem
    lote_id TEXT NOT NULL,
    leilao_id TEXT,

    -- === DADOS BRUTOS ===
    -- Payload completo da API (JSON)
    api_response JSONB NOT NULL,

    -- === CLASSIFICACAO ===
    -- Tipo do leilao: 1=presencial, 2=online, 3=hibrido (excluir)
    tipo INTEGER,
    categoria TEXT,

    -- === CONTROLE DE PROCESSAMENTO ===
    -- Status: pending (aguardando), processed (normalizado), rejected (rejeitado)
    processing_status TEXT DEFAULT 'pending'
        CHECK (processing_status IN ('pending', 'processed', 'rejected')),
    processed_at TIMESTAMPTZ,
    rejection_reason TEXT,

    -- === METADADOS DE COLETA ===
    -- Identificador da execucao do pipeline
    run_id TEXT,
    -- Pagina da API de onde veio
    api_page INTEGER,
    -- Endpoint usado
    api_endpoint TEXT DEFAULT '/core/api/get-lotes',
    -- Status HTTP da resposta
    http_status INTEGER,
    -- Momento da coleta
    fetched_at TIMESTAMPTZ DEFAULT NOW(),

    -- === TIMESTAMPS ===
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- === CONSTRAINTS ===
    -- Garante unicidade por hash de conteudo
    CONSTRAINT uq_leiloeiro_raw_content_hash UNIQUE (content_hash)
);

-- ============================================================================
-- FASE 2: CRIAR INDICES
-- ============================================================================

-- Indice para busca por hash (idempotencia)
CREATE INDEX IF NOT EXISTS idx_leiloeiro_raw_content_hash
    ON public.leiloeiro_lotes_raw(content_hash);

-- Indice para busca por status de processamento
CREATE INDEX IF NOT EXISTS idx_leiloeiro_raw_status
    ON public.leiloeiro_lotes_raw(processing_status);

-- Indice para busca por lote_id
CREATE INDEX IF NOT EXISTS idx_leiloeiro_raw_lote_id
    ON public.leiloeiro_lotes_raw(lote_id);

-- Indice para filtrar por tipo (excluir tipo=3)
CREATE INDEX IF NOT EXISTS idx_leiloeiro_raw_tipo
    ON public.leiloeiro_lotes_raw(tipo);

-- Indice para busca por run_id (rastreabilidade)
CREATE INDEX IF NOT EXISTS idx_leiloeiro_raw_run_id
    ON public.leiloeiro_lotes_raw(run_id);

-- Indice para ordenacao por data de coleta
CREATE INDEX IF NOT EXISTS idx_leiloeiro_raw_fetched_at
    ON public.leiloeiro_lotes_raw(fetched_at DESC);

-- ============================================================================
-- FASE 3: TRIGGER PARA updated_at
-- ============================================================================

-- Usa a funcao existente update_updated_at_column()
-- Se nao existir, cria
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_proc
        WHERE proname = 'update_updated_at_column'
    ) THEN
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $func$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $func$ LANGUAGE plpgsql;
    END IF;
END $$;

CREATE TRIGGER update_leiloeiro_raw_updated_at
    BEFORE UPDATE ON public.leiloeiro_lotes_raw
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- FASE 4: RLS (Row Level Security)
-- ============================================================================

ALTER TABLE public.leiloeiro_lotes_raw ENABLE ROW LEVEL SECURITY;

-- Service role tem acesso total (para o pipeline)
CREATE POLICY "Service role full access leiloeiro_raw"
    ON public.leiloeiro_lotes_raw
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Usuarios autenticados podem ler (para debugging no dashboard admin)
CREATE POLICY "Authenticated read leiloeiro_raw"
    ON public.leiloeiro_lotes_raw
    FOR SELECT
    TO authenticated
    USING (true);

-- ============================================================================
-- FASE 5: COMENTARIOS
-- ============================================================================

COMMENT ON TABLE public.leiloeiro_lotes_raw IS
'Tabela staging para dados brutos da API leiloesjudiciais.com.br.
Armazena payloads completos antes da normalizacao.
Usa content_hash para garantir idempotencia em reruns.';

COMMENT ON COLUMN public.leiloeiro_lotes_raw.content_hash IS
'Hash SHA256 do payload para detectar duplicatas';

COMMENT ON COLUMN public.leiloeiro_lotes_raw.processing_status IS
'Status: pending (aguardando), processed (normalizado com sucesso), rejected (falhou validacao)';

COMMENT ON COLUMN public.leiloeiro_lotes_raw.tipo IS
'Tipo do leilao: 1=presencial, 2=online, 3=hibrido. Tipo 3 deve ser rejeitado.';

-- ============================================================================
-- VERIFICACAO FINAL
-- ============================================================================

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'leiloeiro_lotes_raw') THEN
        RAISE NOTICE '========================================';
        RAISE NOTICE 'MIGRACAO 010 CONCLUIDA!';
        RAISE NOTICE '========================================';
        RAISE NOTICE 'Tabela: public.leiloeiro_lotes_raw';
        RAISE NOTICE 'Proposito: Staging para dados brutos da API';
        RAISE NOTICE 'Indices: content_hash, status, lote_id, tipo, run_id';
        RAISE NOTICE 'RLS: Habilitado (service_role full, authenticated read)';
        RAISE NOTICE '========================================';
    ELSE
        RAISE EXCEPTION 'ERRO: Tabela leiloeiro_lotes_raw nao foi criada!';
    END IF;
END $$;
