-- ============================================================================
-- MIGRACAO 011: Criar tabela normalizada leiloeiro_lotes
-- Data: 2026-01-30
-- Autor: Claude Code
-- Descricao: Tabela para lotes normalizados prontos para o dashboard.
--            Schema alinhado com o contrato canonico do projeto.
-- ============================================================================

-- ============================================================================
-- FASE 1: CRIAR TABELA leiloeiro_lotes
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.leiloeiro_lotes (
    -- Identificador primario
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- === IDENTIFICACAO ===
    -- ID interno unico no formato "leiloesjudiciais|{hash}"
    id_interno TEXT NOT NULL UNIQUE,
    -- IDs originais da API
    lote_id_original TEXT NOT NULL,
    leilao_id_original TEXT,

    -- === DADOS DO LOTE ===
    titulo TEXT NOT NULL,
    descricao TEXT,
    objeto_resumido TEXT,

    -- === LOCALIZACAO ===
    cidade TEXT,
    uf CHAR(2),

    -- === DATAS ===
    -- Data do leilao (dt_fechamento da API, ISO 8601 com timezone)
    data_leilao TIMESTAMPTZ,
    data_publicacao DATE,

    -- === VALORES ===
    valor_avaliacao NUMERIC(15, 2),
    valor_lance_inicial NUMERIC(15, 2),
    valor_incremento NUMERIC(15, 2),

    -- === LINKS ===
    -- URL do lote no site do leiloeiro
    link_leiloeiro TEXT,
    -- URL do edital (prioridade: EDITAL RETIFICADO > EDITAL)
    link_edital TEXT,

    -- === CLASSIFICACAO ===
    -- Tags geradas a partir do conteudo
    tags TEXT[] NOT NULL DEFAULT '{}',
    -- Categoria original da API
    categoria TEXT,
    -- Tipo: 'presencial', 'online'
    tipo_leilao TEXT,

    -- === ORGANIZACAO ===
    orgao TEXT DEFAULT 'Leilao Judicial',
    nome_leiloeiro TEXT,
    n_edital TEXT,

    -- === ORIGEM (alinhado com contrato canonico) ===
    source_type TEXT NOT NULL DEFAULT 'leiloeiro'
        CHECK (source_type = 'leiloeiro'),
    source_name TEXT NOT NULL DEFAULT 'Leiloes Judiciais',

    -- === METADADOS ===
    -- Dados extras especificos da fonte
    metadata JSONB DEFAULT '{}',
    -- Lista de URLs de imagens
    imagens TEXT[] DEFAULT '{}',

    -- === QUALIDADE ===
    -- Score de confianca (0-100)
    confidence_score INTEGER DEFAULT 50
        CHECK (confidence_score >= 0 AND confidence_score <= 100),
    -- Status de publicacao
    publication_status TEXT DEFAULT 'published'
        CHECK (publication_status IN ('draft', 'published', 'archived')),

    -- === RASTREABILIDADE ===
    -- FK para tabela raw (proveniencia)
    raw_id BIGINT REFERENCES public.leiloeiro_lotes_raw(id),
    -- Versao do pipeline que processou
    versao_pipeline TEXT DEFAULT 'v1.0',

    -- === TIMESTAMPS ===
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- FASE 2: CRIAR INDICES
-- ============================================================================

-- Indice para busca por id_interno (principal)
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_id_interno
    ON public.leiloeiro_lotes(id_interno);

-- Indice para busca por data do leilao (filtro principal)
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_data_leilao
    ON public.leiloeiro_lotes(data_leilao DESC);

-- Indice para filtro por UF
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_uf
    ON public.leiloeiro_lotes(uf);

-- Indice para filtro por cidade
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_cidade
    ON public.leiloeiro_lotes(cidade);

-- Indice para filtro por status de publicacao
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_status
    ON public.leiloeiro_lotes(publication_status);

-- Indice GIN para busca por tags
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_tags
    ON public.leiloeiro_lotes USING GIN(tags);

-- Indice para busca por lote_id original
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_lote_id_original
    ON public.leiloeiro_lotes(lote_id_original);

-- Indice composto para chave unica de negocio
CREATE INDEX IF NOT EXISTS idx_leiloeiro_lotes_source_lote
    ON public.leiloeiro_lotes(source_name, lote_id_original);

-- ============================================================================
-- FASE 3: TRIGGER PARA updated_at
-- ============================================================================

CREATE TRIGGER update_leiloeiro_lotes_updated_at
    BEFORE UPDATE ON public.leiloeiro_lotes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- FASE 4: RLS (Row Level Security)
-- ============================================================================

ALTER TABLE public.leiloeiro_lotes ENABLE ROW LEVEL SECURITY;

-- Service role tem acesso total (para o pipeline)
CREATE POLICY "Service role full access leiloeiro_lotes"
    ON public.leiloeiro_lotes
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Usuarios anonimos podem ler apenas lotes publicados
CREATE POLICY "Anon read published leiloeiro_lotes"
    ON public.leiloeiro_lotes
    FOR SELECT
    TO anon
    USING (publication_status = 'published');

-- Usuarios autenticados podem ler apenas lotes publicados
CREATE POLICY "Authenticated read published leiloeiro_lotes"
    ON public.leiloeiro_lotes
    FOR SELECT
    TO authenticated
    USING (publication_status = 'published');

-- ============================================================================
-- FASE 5: FUNCAO AUXILIAR PARA UPSERT
-- ============================================================================

-- Funcao para inserir ou atualizar lote (idempotencia)
CREATE OR REPLACE FUNCTION public.upsert_leiloeiro_lote(
    p_id_interno TEXT,
    p_lote_id_original TEXT,
    p_leilao_id_original TEXT,
    p_titulo TEXT,
    p_descricao TEXT,
    p_objeto_resumido TEXT,
    p_cidade TEXT,
    p_uf CHAR(2),
    p_data_leilao TIMESTAMPTZ,
    p_valor_avaliacao NUMERIC,
    p_link_leiloeiro TEXT,
    p_link_edital TEXT,
    p_tags TEXT[],
    p_categoria TEXT,
    p_tipo_leilao TEXT,
    p_nome_leiloeiro TEXT,
    p_imagens TEXT[],
    p_metadata JSONB,
    p_confidence_score INTEGER,
    p_raw_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    INSERT INTO public.leiloeiro_lotes (
        id_interno, lote_id_original, leilao_id_original,
        titulo, descricao, objeto_resumido,
        cidade, uf, data_leilao,
        valor_avaliacao, link_leiloeiro, link_edital,
        tags, categoria, tipo_leilao,
        nome_leiloeiro, imagens, metadata,
        confidence_score, raw_id, data_publicacao
    )
    VALUES (
        p_id_interno, p_lote_id_original, p_leilao_id_original,
        p_titulo, p_descricao, p_objeto_resumido,
        p_cidade, p_uf, p_data_leilao,
        p_valor_avaliacao, p_link_leiloeiro, p_link_edital,
        COALESCE(p_tags, '{}'), p_categoria, p_tipo_leilao,
        p_nome_leiloeiro, COALESCE(p_imagens, '{}'), COALESCE(p_metadata, '{}'),
        COALESCE(p_confidence_score, 50), p_raw_id, CURRENT_DATE
    )
    ON CONFLICT (id_interno) DO UPDATE SET
        titulo = EXCLUDED.titulo,
        descricao = EXCLUDED.descricao,
        objeto_resumido = EXCLUDED.objeto_resumido,
        cidade = EXCLUDED.cidade,
        uf = EXCLUDED.uf,
        data_leilao = EXCLUDED.data_leilao,
        valor_avaliacao = EXCLUDED.valor_avaliacao,
        link_leiloeiro = EXCLUDED.link_leiloeiro,
        link_edital = EXCLUDED.link_edital,
        tags = EXCLUDED.tags,
        metadata = EXCLUDED.metadata,
        confidence_score = EXCLUDED.confidence_score,
        updated_at = NOW()
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.upsert_leiloeiro_lote TO service_role;

-- ============================================================================
-- FASE 6: COMENTARIOS
-- ============================================================================

COMMENT ON TABLE public.leiloeiro_lotes IS
'Tabela normalizada de lotes do leiloeiro leiloesjudiciais.com.br.
Schema alinhado com o contrato canonico para integracao com o dashboard.
Usa source_type=leiloeiro para diferenciacao do PNCP.';

COMMENT ON COLUMN public.leiloeiro_lotes.id_interno IS
'ID unico no formato "leiloesjudiciais|{hash}" para identificacao global';

COMMENT ON COLUMN public.leiloeiro_lotes.data_leilao IS
'Data e hora do fechamento do leilao (dt_fechamento da API) em ISO 8601';

COMMENT ON COLUMN public.leiloeiro_lotes.link_edital IS
'URL do edital. Prioridade: EDITAL RETIFICADO > EDITAL > NULL';

COMMENT ON COLUMN public.leiloeiro_lotes.tags IS
'Tags geradas a partir do titulo/descricao. Ex: CARRO, SUCATA, VEICULO';

COMMENT ON COLUMN public.leiloeiro_lotes.raw_id IS
'FK para leiloeiro_lotes_raw - rastreabilidade da origem';

-- ============================================================================
-- VERIFICACAO FINAL
-- ============================================================================

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'leiloeiro_lotes') THEN
        RAISE NOTICE '========================================';
        RAISE NOTICE 'MIGRACAO 011 CONCLUIDA!';
        RAISE NOTICE '========================================';
        RAISE NOTICE 'Tabela: public.leiloeiro_lotes';
        RAISE NOTICE 'Proposito: Lotes normalizados para dashboard';
        RAISE NOTICE 'Campos principais: id_interno, titulo, data_leilao, tags';
        RAISE NOTICE 'Funcao: upsert_leiloeiro_lote() para idempotencia';
        RAISE NOTICE 'RLS: Habilitado (anon/authenticated read published)';
        RAISE NOTICE '========================================';
    ELSE
        RAISE EXCEPTION 'ERRO: Tabela leiloeiro_lotes nao foi criada!';
    END IF;
END $$;
