-- ============================================================================
-- MIGRACAO 012: Criar tabela de quarentena para lotes rejeitados
-- Data: 2026-01-30
-- Autor: Claude Code
-- Descricao: Dead Letter Queue para lotes que falharam na validacao.
--            Permite analise e reprocessamento de registros problematicos.
-- ============================================================================

-- ============================================================================
-- FASE 1: CRIAR TABELA leiloeiro_quarantine
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.leiloeiro_quarantine (
    -- Identificador primario
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- === REFERENCIA AO REGISTRO RAW ===
    raw_id BIGINT REFERENCES public.leiloeiro_lotes_raw(id),

    -- === IDENTIFICACAO DO ITEM ===
    -- ID interno tentado
    id_interno TEXT,
    -- ID original do lote na API
    lote_id_original TEXT,

    -- === MOTIVO DA REJEICAO ===
    -- Codigo padronizado do erro
    rejection_code TEXT NOT NULL,
    -- Mensagem descritiva do erro
    rejection_reason TEXT NOT NULL,
    -- Lista de todos os erros de validacao
    validation_errors TEXT[] DEFAULT '{}',

    -- === PAYLOAD ORIGINAL ===
    -- Dados brutos para analise e reprocessamento
    payload_original JSONB NOT NULL,
    -- Dados normalizados (se chegou nessa fase)
    normalized_data JSONB,

    -- === METADADOS DE PROCESSAMENTO ===
    -- ID da execucao do pipeline
    run_id TEXT,
    -- Versao do pipeline
    pipeline_version TEXT DEFAULT 'v1.0',
    -- Fase em que falhou
    failed_at_stage TEXT DEFAULT 'validation'
        CHECK (failed_at_stage IN ('fetch', 'normalize', 'validation', 'persist')),
    -- Momento do processamento
    processed_at TIMESTAMPTZ DEFAULT NOW(),

    -- === RESOLUCAO ===
    -- Status: pending (aguardando), resolved (resolvido), discarded (descartado)
    status TEXT DEFAULT 'pending'
        CHECK (status IN ('pending', 'resolved', 'discarded')),
    -- Quando foi resolvido
    resolved_at TIMESTAMPTZ,
    -- Quem resolveu
    resolved_by TEXT,
    -- Notas de resolucao
    resolution_notes TEXT,

    -- === TIMESTAMPS ===
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- FASE 2: CRIAR INDICES
-- ============================================================================

-- Indice para filtrar por status
CREATE INDEX IF NOT EXISTS idx_leiloeiro_quarantine_status
    ON public.leiloeiro_quarantine(status);

-- Indice para agrupar por codigo de rejeicao
CREATE INDEX IF NOT EXISTS idx_leiloeiro_quarantine_code
    ON public.leiloeiro_quarantine(rejection_code);

-- Indice para busca por run_id
CREATE INDEX IF NOT EXISTS idx_leiloeiro_quarantine_run_id
    ON public.leiloeiro_quarantine(run_id);

-- Indice para busca por lote_id
CREATE INDEX IF NOT EXISTS idx_leiloeiro_quarantine_lote_id
    ON public.leiloeiro_quarantine(lote_id_original);

-- Indice para ordenacao por data
CREATE INDEX IF NOT EXISTS idx_leiloeiro_quarantine_created_at
    ON public.leiloeiro_quarantine(created_at DESC);

-- ============================================================================
-- FASE 3: TRIGGER PARA updated_at
-- ============================================================================

CREATE TRIGGER update_leiloeiro_quarantine_updated_at
    BEFORE UPDATE ON public.leiloeiro_quarantine
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- FASE 4: RLS (Row Level Security)
-- ============================================================================

ALTER TABLE public.leiloeiro_quarantine ENABLE ROW LEVEL SECURITY;

-- Service role tem acesso total (para o pipeline)
CREATE POLICY "Service role full access leiloeiro_quarantine"
    ON public.leiloeiro_quarantine
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Usuarios autenticados podem ler (para analise no admin)
CREATE POLICY "Authenticated read leiloeiro_quarantine"
    ON public.leiloeiro_quarantine
    FOR SELECT
    TO authenticated
    USING (true);

-- ============================================================================
-- FASE 5: DEFINIR CODIGOS DE REJEICAO (ENUM LOGICO)
-- ============================================================================

-- Tabela de referencia para codigos de rejeicao
CREATE TABLE IF NOT EXISTS public.leiloeiro_rejection_codes (
    code TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    severity TEXT DEFAULT 'error'
        CHECK (severity IN ('warning', 'error', 'fatal')),
    is_recoverable BOOLEAN DEFAULT false
);

-- Inserir codigos padrao
INSERT INTO public.leiloeiro_rejection_codes (code, description, severity, is_recoverable)
VALUES
    ('TIPO_3', 'Leilao tipo 3 (hibrido) nao suportado pelo escopo', 'fatal', false),
    ('MISSING_DATA_LEILAO', 'Campo obrigatorio data_leilao ausente', 'error', true),
    ('MISSING_TAGS', 'Campo obrigatorio tags ausente ou vazio', 'error', true),
    ('INVALID_UF', 'UF invalida ou nao reconhecida', 'error', true),
    ('INVALID_TITULO', 'Titulo ausente ou invalido', 'error', true),
    ('MISSING_ID_INTERNO', 'Falha ao gerar id_interno', 'fatal', false),
    ('DUPLICATE_CONTENT', 'Conteudo duplicado (mesmo content_hash)', 'warning', false),
    ('API_ERROR', 'Erro ao buscar dados da API', 'error', true),
    ('PARSE_ERROR', 'Erro ao parsear resposta da API', 'error', true),
    ('CATEGORY_EXCLUDED', 'Categoria excluida do escopo (ex: imoveis)', 'fatal', false),
    ('EXPIRED_AUCTION', 'Leilao ja encerrado', 'warning', false)
ON CONFLICT (code) DO NOTHING;

-- ============================================================================
-- FASE 6: FUNCAO PARA INSERIR NA QUARENTENA
-- ============================================================================

CREATE OR REPLACE FUNCTION public.quarantine_leiloeiro_lote(
    p_raw_id BIGINT,
    p_id_interno TEXT,
    p_lote_id_original TEXT,
    p_rejection_code TEXT,
    p_rejection_reason TEXT,
    p_validation_errors TEXT[],
    p_payload_original JSONB,
    p_normalized_data JSONB,
    p_run_id TEXT,
    p_failed_at_stage TEXT DEFAULT 'validation'
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    INSERT INTO public.leiloeiro_quarantine (
        raw_id, id_interno, lote_id_original,
        rejection_code, rejection_reason, validation_errors,
        payload_original, normalized_data,
        run_id, failed_at_stage
    )
    VALUES (
        p_raw_id, p_id_interno, p_lote_id_original,
        p_rejection_code, p_rejection_reason, COALESCE(p_validation_errors, '{}'),
        p_payload_original, p_normalized_data,
        p_run_id, COALESCE(p_failed_at_stage, 'validation')
    )
    RETURNING id INTO v_id;

    -- Atualiza status do raw para rejected
    IF p_raw_id IS NOT NULL THEN
        UPDATE public.leiloeiro_lotes_raw
        SET processing_status = 'rejected',
            rejection_reason = p_rejection_code,
            processed_at = NOW()
        WHERE id = p_raw_id;
    END IF;

    RETURN v_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.quarantine_leiloeiro_lote TO service_role;

-- ============================================================================
-- FASE 7: VIEW PARA ANALISE DE QUARENTENA
-- ============================================================================

CREATE OR REPLACE VIEW public.v_leiloeiro_quarantine_summary AS
SELECT
    rejection_code,
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE status = 'resolved') AS resolved,
    COUNT(*) FILTER (WHERE status = 'discarded') AS discarded,
    MIN(created_at) AS first_occurrence,
    MAX(created_at) AS last_occurrence
FROM public.leiloeiro_quarantine
GROUP BY rejection_code
ORDER BY total DESC;

COMMENT ON VIEW public.v_leiloeiro_quarantine_summary IS
'Resumo de erros na quarentena por codigo de rejeicao';

-- ============================================================================
-- FASE 8: COMENTARIOS
-- ============================================================================

COMMENT ON TABLE public.leiloeiro_quarantine IS
'Dead Letter Queue para lotes que falharam na validacao.
Permite analise de erros e eventual reprocessamento.
Status: pending (aguardando analise), resolved (corrigido), discarded (ignorado).';

COMMENT ON COLUMN public.leiloeiro_quarantine.rejection_code IS
'Codigo padronizado do erro. Ver tabela leiloeiro_rejection_codes para descricoes.';

COMMENT ON COLUMN public.leiloeiro_quarantine.payload_original IS
'Dados brutos da API para analise e reprocessamento';

COMMENT ON COLUMN public.leiloeiro_quarantine.failed_at_stage IS
'Fase do pipeline onde ocorreu o erro: fetch, normalize, validation, persist';

-- ============================================================================
-- VERIFICACAO FINAL
-- ============================================================================

DO $$
DECLARE
    v_rejection_codes_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_rejection_codes_count FROM public.leiloeiro_rejection_codes;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'leiloeiro_quarantine') THEN
        RAISE NOTICE '========================================';
        RAISE NOTICE 'MIGRACAO 012 CONCLUIDA!';
        RAISE NOTICE '========================================';
        RAISE NOTICE 'Tabela: public.leiloeiro_quarantine';
        RAISE NOTICE 'Proposito: Dead Letter Queue para lotes rejeitados';
        RAISE NOTICE 'Codigos de rejeicao cadastrados: %', v_rejection_codes_count;
        RAISE NOTICE 'Funcao: quarantine_leiloeiro_lote() para insercao';
        RAISE NOTICE 'View: v_leiloeiro_quarantine_summary para analise';
        RAISE NOTICE 'RLS: Habilitado (service_role full, authenticated read)';
        RAISE NOTICE '========================================';
    ELSE
        RAISE EXCEPTION 'ERRO: Tabela leiloeiro_quarantine nao foi criada!';
    END IF;
END $$;
